### ISSUE TITLE
No download info given for 'kvtree'

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr-top#1]
I haven't taken any time to dive into this, so it may be something simple.  I gave this a shot
```
git clone https://github.com/llnl/scr-top scr-top.git
cd scr-top.git

mkdir build
cd build
cmake ../
```
and hit the following error:
```
CMake Error at /usr/tce/packages/cmake/cmake-3.14.5/share/cmake/Modules/ExternalProject.cmake:2628 (message):
  No download info given for 'kvtree' and its source directory:

   /g/g0/user1/packages/scr-top.git/kvtree

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
```

**Comment by gonsie** [comment]
run `make clone` in the top level directory first.

We could encode the cloning information into CMake, but I think this would make it more difficult to package everything in to a single distribution.

**Comment by adammoody** [comment]
Ah, thanks.  That did it.  I did have to delete my "scr" directory to get "make clone" to do anything after I had messed it up after missing make clone step the first time.

**Comment by adammoody** [comment]
Do you prefer to add a ```make clone``` step in the README or change ```make build``` to imply the clone step?

**Comment by gonsie** [comment]
I’ll add that explicitly to the readMe. I think I originally had build depend on clone, but that could have cloned over anything you unpacked.
